### ISSUE TITLE
Contact form 

### ISSUE THREAD

**Issue by Kidfalcon** [Bottle-Co/bottle-web#17]
Add a contact form as a separate section underneath how we do, It should feature content on the left side and form fields on the right side.

Content : We offer customizable masks for brands, corporates, events, bulk buyers, wholesalers etc.
We love talking about our mission and products. Are you a business? Get in touch with us to know how we can create value for you!

Form fields :  Name, email, Message

**Comment by Kidfalcon** [comment]
Contact form update:- Will keep the full contact form/mailchimp intergration on pause, For the time being

Just add a seperate section which has a box.

Inside the box, Content is featured on the left side, On the right side we have our email (info@bottlenco) along with email icons/messenger icon.

**Comment by vreddi** [comment]
https://mailgo.dev/
